- name: Build Debug APK (log detail)
        run: |
          export ANDROID_HOME=/usr/local/lib/android/sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
          chmod +x gradlew || true
          ./gradlew clean
          ./gradlew projects
          ./gradlew :app:assembleDebug --stacktrace --info
          echo "========== Cek file APK =========="
          find app/build -type f -name "*.apk" || echo "‚ùå Tidak ditemukan APK sama sekali"